### ISSUE TITLE
Contact Agent module for bottom of page

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/mlmrealtyatx.com#12]
Make Contact Agent from Homepage (sitting at the bottom of the content area) a module that can be placed on other pages.

Double-check "Submit" button formatting (it should look more like a button and be green; see comp) and spacing of that module against comp.

Also can we add the same fields that should appear on the "Contact" page?

![image](https://cloud.githubusercontent.com/assets/20050245/26117485/59269294-3a2c-11e7-9fa4-8a4672df7e33.png)

**Comment by vcfolger** [comment]
I should have asked, how can I add the Contact module from the the homepage to other pages?

**Comment by joshbolinger** [comment]
just add this


[contact-form-7 id="35" title="Contact Agent"]

**Comment by vcfolger** [comment]
That does stick the form fields in, but what I was looking for was to add this nice module that we have under "home"
![screen shot 2017-05-21 at 1 17 12 pm](https://cloud.githubusercontent.com/assets/20050245/26286317/df3b4f88-3e27-11e7-971f-49442199db15.png)

**Comment by joshbolinger** [comment]
Im not really sure what you are asking

**Comment by vcfolger** [comment]
See the above screenshot. I wanted to have the "Contact Agent" section of the homepage be a module that can be used at the bottom of other pages. 

I think what you gave me were instructions on how to insert the contact form fields into the site, but not the whole "Contact Agent" section from home as it appears above.

**Comment by joshbolinger** [comment]
do you want to just put it at the bottom of all pages? Right now its hard coded

**Comment by vcfolger** [comment]
Ah ok. Sure let's put it at the bottom of every page. Thanks
