### ISSUE TITLE
Homepage left vertical bar/where Home Search was

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/mlmrealtyatx.com#18]
Josh,
The left vertical space looks empty (because we had to remove that Home Search element). Would it be too much trouble to tighten the bar up close to the edges of the logo so it does not look as bad? Then we could widen again when we add Home Search back?

**Comment by vcfolger** [comment]
Is this done or did you close it because we can't do it?

**Comment by joshbolinger** [comment]
well I center aligned the whole nav. Is that not what you wanted?

**Comment by vcfolger** [comment]
What you did with the nav looks good. One thing that somehow got messed up is that "Sell" should come after "Buy/Invest" in the nav, so left-to-right, it would be "Buy/Invest" and then "Sell".

What I was asking in this issue was to make the width of the **grey overlay** that runs top-to-bottom underneath the logo narrower.
