### ISSUE TITLE
Featured Listings/Home

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/mlmrealtyatx.com#2]
Can we hide Featured Listings section on the homepage? We need to launch without this part, but may be able to add back in later. OR alternatively, we could manually load some photos/descriptions into this area but it would not be dynamic. Thoughts?

**Comment by joshbolinger** [comment]
I added a new section in the admin for editing these

http://mlmrealtyatx.com/wp-admin/edit.php?post_type=property
