### ISSUE TITLE
Add more margin above H2

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/mlmrealtyatx.com#27]
Not sure if this is the same for H1/H2/H3, but it probably should be. I'm noticing that the H2s would look better if there was more margin above them to space them out from text just above. Example here.
![screen shot 2017-05-24 at 2 10 04 pm](https://cloud.githubusercontent.com/assets/20050245/26421189/ba2116aa-408a-11e7-81a1-1701a6831046.png)

**Comment by joshbolinger** [comment]
those really should be H3s not H2s
