### ISSUE TITLE
Home Search FYI

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/mlmrealtyatx.com#6]
http://www.abor.com/blog-matrix-client-portal-updates/

There is a new release coming that we may be able to leverage, without paying for a plugin. Looks like the results display is much improved, but "Search" still looks crappy. We might have to live with that. I'm not totally clear on whether this is a website integration piece, or a separate site that consumers can log in to....

**Comment by joshbolinger** [comment]
oh nice, looks like we can use some of this
