### ISSUE TITLE
Testimonial Modules/how to update text

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/mlmrealtyatx.com#8]
Can you tell me how I update the content in the Testimonial quotes, both for the homepage sliders and in the right side modules?

**Comment by joshbolinger** [comment]
theres a custom post type here

http://mlmrealtyatx.com/wp-admin/edit.php?post_type=testimonial

**Comment by vcfolger** [comment]
I added some fake testimonials in there. A couple of questions though:
- Where is the testimonial on "Contact" coming from? 
- We were thinking that the homepage would include a different testimonial with each slider, but it looks like it's not built that way... Could we make that text area change every time the banner changes? Or would we have to make the testimonials part of the banner images for it to do that?
