### ISSUE TITLE
Home Search/Right Column Module

### ISSUE THREAD

**Issue by vcfolger** [vcfolger/mlmrealtyatx.com#9]
How can I insert/remove the "Home Search" module on the right side of the interior pages? We will need to launch without these but I would like to be able to add it back in later.

**Comment by vcfolger** [comment]
Can you answer the question?
( How can I insert/remove the "Home Search" module on the right side of the interior pages? )

**Comment by joshbolinger** [comment]
it wasnt functional before. Once we install IDK there will be a Widget under Appearance
